const SAVE_KEY='tu-tien-du-hanh-mvp-v1';
const W=12,H=8;
const professions={
  technology:{name:'Công nghệ kỹ thuật',bonus:'Trận pháp +12%',attack:2,spirit:4},
  medical:{name:'Y tế dược',bonus:'Hồi phục +20%',attack:0,spirit:6},
  education:{name:'Giáo dục nghiên cứu',bonus:'Lĩnh ngộ +15%',attack:1,spirit:5},
  business:{name:'Kinh doanh tài chính',bonus:'Linh thạch +12%',attack:1,spirit:2},
  art:{name:'Nghệ thuật truyền thông',bonus:'Cơ duyên +10%',attack:2,spirit:3},
  service:{name:'Dịch vụ du lịch',bonus:'Linh khí địa điểm +12%',attack:1,spirit:4},
  logistics:{name:'Vận tải logistics',bonus:'Khám phá +15%',attack:3,spirit:1},
  nature:{name:'Nông nghiệp tự nhiên',bonus:'Thu thập +18%',attack:2,spirit:3},
  student:{name:'Học sinh sinh viên',bonus:'Học công pháp -15% chi phí',attack:0,spirit:5},
  freelance:{name:'Tự do',bonus:'Cơ duyên linh hoạt +6%',attack:2,spirit:2}
};
const techniques=[
  {id:'breath',name:'Dẫn Khí Quyết',desc:'Tu luyện ổn định, tăng 15% tu vi nhận được.',cost:0,all:true},
  {id:'seek',name:'Tầm Linh Bí Thuật',desc:'Thần thức nhìn xa hơn và tăng cơ hội tìm rương.',cost:80,all:true},
  {id:'overcome',name:'Nghịch Mạch Tam Kích',desc:'Sát thương bùng nổ +60%, nhưng mỗi đòn mất 6 sinh lực.',cost:160,all:true},
  {id:'extreme',name:'Cực Cảnh Luyện Khí',desc:'Khóa tại Luyện Khí viên mãn; tăng 35% toàn bộ chỉ số chiến đấu.',cost:260,all:true,lockRealm:true},
  {id:'profession',name:'Bách Nghệ Tâm Kinh',desc:'Công pháp theo nghề, nhân đôi thuộc tính nghề nghiệp.',cost:120,profession:true}
];
const itemPool=[
  {name:'Mộc Kiếm',icon:'🗡️',slot:'weapon',atk:3,rarity:'Phàm'}, {name:'Thanh Phong Kiếm',icon:'⚔️',slot:'weapon',atk:8,rarity:'Linh'},
  {name:'Đạo Bào',icon:'🥋',slot:'armor',def:4,rarity:'Phàm'}, {name:'Huyền Giáp',icon:'🛡️',slot:'armor',def:9,rarity:'Huyền'},
  {name:'Tụ Linh Đan',icon:'💊',slot:'consumable',heal:35,rarity:'Linh'}, {name:'Mảnh Công Pháp',icon:'📜',slot:'material',rarity:'Huyền'}
];
const defaultState=()=>({version:1,created:false,name:'Vô Danh',profession:'freelance',level:1,realm:0,realmStage:1,xp:0,hp:100,mp:60,stones:20,fortune:3,pos:{x:5,y:4},inventory:[],equipment:{},learned:['breath'],activeTechnique:'breath',cultivation:null,lastSeen:Date.now(),logs:[],worldSeed:Math.floor(Math.random()*999999),events:[],settings:{monsterRate:13,chestRate:5,rareRate:2,auraMultiplier:100}});
let state=load(); let world=[]; let combat=null; let scanUntil=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function load(){try{return Object.assign(defaultState(),JSON.parse(localStorage.getItem(SAVE_KEY)||'{}'))}catch{return defaultState()}}
function save(){state.lastSeen=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(state));$('#saveStatus').textContent='Đã lưu';}
function rng(n=1){let x=Math.sin(state.worldSeed++)*10000;return(x-Math.floor(x))*n}
function log(text){state.logs.unshift({text,time:new Date().toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})});state.logs=state.logs.slice(0,24)}
function toast(text){const e=$('#toast');e.textContent=text;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function xpNeed(){return 60+state.level*35}
function stats(){const p=professions[state.profession],eq=Object.values(state.equipment);let atk=8+state.level*2+p.attack,def=3+state.level,spirit=10+p.spirit;if(state.activeTechnique==='profession'){atk+=p.attack;spirit+=p.spirit}if(state.activeTechnique==='extreme'){atk=Math.round(atk*1.35);def=Math.round(def*1.35)}for(const i of eq){atk+=i.atk||0;def+=i.def||0}return{atk,def,spirit,maxHp:100+state.level*8,maxMp:60+spirit*2}}
function addXp(v){if(state.activeTechnique==='breath')v=Math.round(v*1.15);state.xp+=v;while(state.xp>=xpNeed()){state.xp-=xpNeed();state.level++;state.hp=stats().maxHp;state.mp=stats().maxMp;log(`<b>Đột phá</b> lên cấp ${state.level}`);toast('Cảnh giới tiến triển!')} }
function generateWorld(){world=[];for(let y=0;y<H;y++)for(let x=0;x<W;x++){const roll=rng(100);let type='ground';if((x+y)%17===0)type='water';else if((x*3+y)%19===0)type='mountain';const content=roll<state.settings.rareRate?'rare':roll<state.settings.rareRate+4?'elite':roll<state.settings.rareRate+4+state.settings.monsterRate?'monster':roll<state.settings.rareRate+4+state.settings.monsterRate+state.settings.chestRate?'chest':roll>94?'aura':null;world.push({x,y,type,content,seen:Math.abs(x-state.pos.x)+Math.abs(y-state.pos.y)<=2})}}
function tileAt(x,y){return world.find(t=>t.x===x&&t.y===y)}
function move(dx,dy){const x=state.pos.x+dx,y=state.pos.y+dy;if(x<0||y<0||x>=W||y>=H)return;const t=tileAt(x,y);if(t.type==='water'){toast('Cần thân pháp vượt thủy');return}state.pos={x,y};for(const a of world)if(Math.abs(a.x-x)+Math.abs(a.y-y)<=2)a.seen=true;log(`Di chuyển tới ô ${x+1}-${y+1}`);if(t.content)triggerTile(t);render();save()}
function triggerTile(t){if(['monster','elite','rare'].includes(t.content))startCombat(t);else if(t.content==='chest')openChest(t);else if(t.content==='aura'){const gain=12+Math.floor(rng(12));addXp(gain);state.mp=Math.min(stats().maxMp,state.mp+15);t.content=null;log(`<b>Linh khí hội tụ</b>, nhận ${gain} tu vi`);toast(`+${gain} tu vi`)}}
function startCombat(tile){const rank={monster:1,elite:2,rare:4}[tile.content];combat={tile,rank,name:rank===1?'Yêu Lang':rank===2?'Thiết Bì Hùng':'Xích Viêm Giao',hp:28+rank*24,maxHp:28+rank*24,atk:5+rank*4};showCombat()}
function showCombat(){const s=stats();$('#eventContent').innerHTML=`<h2>⚔️ ${combat.name}</h2><p class="meta">Cấp nguy hiểm ${combat.rank} · Sinh lực ${combat.hp}/${combat.maxHp}</p><p>Ngươi: ${state.hp}/${s.maxHp} HP · Công ${s.atk} · Thủ ${s.def}</p><div class="combat-actions"><button data-fight="attack">Tấn công</button><button data-fight="skill">Vận công</button><button data-fight="heal">Dùng đan</button><button data-fight="run">Rút lui</button></div>`;$('#eventDialog').showModal()}
function fight(action){if(action==='run'){if(rng(100)<65){$('#eventDialog').close();combat=null;toast('Đã rút lui');return}}
  if(action==='heal'){const i=state.inventory.findIndex(x=>x.heal);if(i>=0){state.hp=Math.min(stats().maxHp,state.hp+state.inventory[i].heal);state.inventory.splice(i,1)}else toast('Không có đan dược')}
  else{let dmg=stats().atk+Math.floor(rng(7));if(action==='skill'){if(state.mp<10){toast('Không đủ linh lực');return}state.mp-=10;dmg=Math.round(dmg*1.55)}if(state.activeTechnique==='overcome'){dmg=Math.round(dmg*1.6);state.hp-=6}combat.hp-=dmg}
  if(combat.hp<=0){winCombat();return}state.hp-=Math.max(1,combat.atk-Math.floor(stats().def/2)+Math.floor(rng(5)));if(state.hp<=0){state.hp=1;state.stones=Math.max(0,state.stones-8);log('<b>Trọng thương</b>, mất 8 linh thạch và trở về trấn');state.pos={x:5,y:4};$('#eventDialog').close();combat=null;toast('Trọng thương!');render();save();return}showCombat();renderHud();save()}
function winCombat(){const r=combat.rank,xp=12*r+Math.floor(rng(8)),stones=5*r+Math.floor(rng(7));addXp(xp);state.stones+=stones;state.fortune+=r===4?2:0;combat.tile.content=null;if(rng(100)<18+r*10)addItem(itemPool[Math.floor(rng(itemPool.length))]);log(`<b>Thắng ${combat.name}</b>, nhận ${xp} tu vi và ${stones} linh thạch`);$('#eventDialog').close();combat=null;toast('Chiến thắng!');render();save()}
function openChest(tile){const tier=rng(100)<8?3:rng(100)<30?2:1;const stones=10*tier+Math.floor(rng(15*tier));state.stones+=stones;addItem(itemPool[Math.min(itemPool.length-1,Math.floor(rng(itemPool.length)+tier-1))]);tile.content=null;log(`<b>Mở rương cấp ${tier}</b>, nhận ${stones} linh thạch và vật phẩm`);toast(`Rương cấp ${tier}!`)}
function addItem(base){state.inventory.push({...base,id:Date.now()+Math.floor(rng(999)),professionBonus:Math.round((base.atk||base.def||2)*.3)});}
function render(){renderHud();renderMap();renderLog();renderCharacter();renderInventory();renderTechniques();renderCultivation();renderRumors();renderAdmin();$('#inventoryBadge').textContent=state.inventory.length;$('#playerName').textContent=state.name;$('#realmText').textContent=`${state.realm?'Luyện Khí':'Phàm Nhân'} tầng ${state.level}`}
function renderHud(){const s=stats();state.hp=Math.min(state.hp,s.maxHp);state.mp=Math.min(state.mp,s.maxMp);$('#hpBar').style.width=`${state.hp/s.maxHp*100}%`;$('#mpBar').style.width=`${state.mp/s.maxMp*100}%`;$('#xpBar').style.width=`${state.xp/xpNeed()*100}%`;$('#hpText').textContent=`${state.hp}/${s.maxHp}`;$('#mpText').textContent=`${state.mp}/${s.maxMp}`;$('#xpText').textContent=`${state.xp}/${xpNeed()}`;$('#spiritStones').textContent=state.stones;$('#fortune').textContent=state.fortune;$('#auraText').textContent=`Linh khí ${state.settings.auraMultiplier}% · cơ duyên ${state.fortune}`}
function renderMap(){const m=$('#map');m.innerHTML='';for(const t of world){const e=document.createElement('div');e.className=`tile ${t.type}`;if(t.content&&(t.seen||Date.now()<scanUntil))e.classList.add(t.content);else if(t.content)e.classList.add('hidden',t.content);if(t.x===state.pos.x&&t.y===state.pos.y)e.classList.add('player');m.appendChild(e)}}
function renderLog(){$('#activityLog').innerHTML=state.logs.map(x=>`<div class="log"><small>${x.time}</small> ${x.text}</div>`).join('')||'<div class="log">Hành trình vừa bắt đầu. Hãy di chuyển để tìm cơ duyên.</div>'}
function renderCharacter(){const s=stats(),p=professions[state.profession];$('#characterContent').innerHTML=`<div class="cards"><article class="card"><h3>${state.name}</h3><p>${p.name}</p><div class="meta">${p.bonus}</div></article><article class="card"><h3>Chỉ số chiến đấu</h3><div class="stats"><div class="stat"><span>Công</span><b>${s.atk}</b></div><div class="stat"><span>Thủ</span><b>${s.def}</b></div><div class="stat"><span>Thần thức</span><b>${s.spirit}</b></div><div class="stat"><span>Cơ duyên</span><b>${state.fortune}</b></div></div></article><article class="card"><h3>Trang bị</h3><p>Vũ khí: ${state.equipment.weapon?.name||'Chưa có'}<br>Pháp bào: ${state.equipment.armor?.name||'Chưa có'}</p></article></div>`}
function renderInventory(){const el=$('#inventoryContent');if(!state.inventory.length){el.innerHTML='<p class="lead">Túi đang trống. Đánh quái hoặc tìm rương trên bản đồ.</p>';return}el.innerHTML=`<div class="cards">${state.inventory.map(i=>`<article class="card item"><span class="item-icon">${i.icon}</span><div><h3>${i.name}</h3><div class="meta">${i.rarity}${i.slot==='weapon'||i.slot==='armor'?` · Đúng nghề +${i.professionBonus}`:''}</div><p>${i.atk?`Công +${i.atk}`:''}${i.def?`Thủ +${i.def}`:''}${i.heal?`Hồi ${i.heal} HP`:''}</p>${['weapon','armor'].includes(i.slot)?`<button data-equip="${i.id}">Trang bị</button>`:''}</div></article>`).join('')}</div>`}
function renderTechniques(){$('#techniqueContent').innerHTML=`<div class="cards">${techniques.map(t=>{const learned=state.learned.includes(t.id),active=state.activeTechnique===t.id;return`<article class="card"><h3>${t.name}</h3><p>${t.desc}</p><div class="meta">${t.profession?'Theo nghề · ':''}${t.cost} linh thạch</div><button data-technique="${t.id}" ${active?'disabled':''}>${active?'Đang vận hành':learned?'Vận hành':'Học công pháp'}</button></article>`}).join('')}</div>`}
function renderCultivation(){const active=state.cultivation&&state.cultivation.end>Date.now();if(active){const left=Math.max(0,Math.ceil((state.cultivation.end-Date.now())/60000));$('#cultivationContent').innerHTML=`<article class="card"><h3>Đang nhập định</h3><p>Còn khoảng ${left} phút. Có thể đóng trình duyệt và quay lại sau.</p><div class="meta">Dự kiến ${state.cultivation.reward} tu vi</div></article>`;return}$('#cultivationContent').innerHTML=`<div class="cards">${[5,15,30,60].map(min=>`<article class="card"><h3>${min} phút</h3><p>Tu luyện tại Thanh Vân Trấn với linh khí ${state.settings.auraMultiplier}%.</p><button data-cultivate="${min}">Bắt đầu nhập định</button></article>`).join('')}</div>`}
function renderRumors(){const rare=world.filter(t=>t.content==='rare').length,chests=world.filter(t=>t.content==='chest').length;$('#rumorContent').innerHTML=`<div class="cards"><article class="card"><h3>Long tức phương đông</h3><p>${rare?'Có khí tức mạnh lướt qua vùng núi. Không rõ còn ở đó bao lâu.':'Khí tức đã tiêu tán, cần chờ cơ duyên mới.'}</p><div class="meta">Dấu hiệu quái hiếm</div></article><article class="card"><h3>Thương nhân say rượu</h3><p>Nghe nói trong vùng hiện có khoảng ${Math.max(1,Math.ceil(chests/2))} đến ${chests+2} rương chưa ai mở.</p><div class="meta">Tin tức không bảo đảm chính xác</div></article></div>`}
function renderAdmin(){const s=state.settings;$('#adminContent').innerHTML=`<div class="cards"><article class="card"><h3>Mật độ thế giới</h3><label>Quái thường <b>${s.monsterRate}%</b><input data-setting="monsterRate" type="range" min="5" max="30" value="${s.monsterRate}"></label><label>Rương <b>${s.chestRate}%</b><input data-setting="chestRate" type="range" min="1" max="15" value="${s.chestRate}"></label><label>Quái hiếm <b>${s.rareRate}%</b><input data-setting="rareRate" type="range" min="1" max="8" value="${s.rareRate}"></label><button id="regenerateWorld">Sinh lại bản đồ</button></article><article class="card"><h3>Linh khí</h3><label>Hệ số <b>${s.auraMultiplier}%</b><input data-setting="auraMultiplier" type="range" min="50" max="250" value="${s.auraMultiplier}"></label><p>Đây là bản thử nghiệm rule engine phía client. Bản production phải cấu hình và kết toán ở máy chủ.</p></article></div>`}
function checkOffline(){const now=Date.now();if(state.cultivation&&state.cultivation.end<=now){addXp(state.cultivation.reward);state.stones+=Math.floor(state.cultivation.reward/8);log(`<b>Hoàn thành tu luyện</b>, nhận ${state.cultivation.reward} tu vi`);state.cultivation=null;toast('Tu luyện hoàn tất')}const away=Math.min(12*60*60*1000,now-state.lastSeen);if(away>10*60*1000){const bonus=Math.floor(away/600000);state.mp=Math.min(stats().maxMp,state.mp+bonus);log(`Trở lại sau ${Math.floor(away/60000)} phút, linh lực hồi phục ${bonus}`)}}
function selectPanel(name){$$('.panel').forEach(x=>x.classList.remove('active'));$(`#${name}Panel`).classList.add('active');$$('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));$('#sidebar').classList.remove('open');render()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.panel)selectPanel(b.dataset.panel);if(b.dataset.move){const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[b.dataset.move];move(...d)}if(b.dataset.fight)fight(b.dataset.fight);if(b.dataset.equip){const i=state.inventory.find(x=>x.id==b.dataset.equip);state.equipment[i.slot]=i;log(`<b>Trang bị</b> ${i.name}`);render();save()}if(b.dataset.technique){const t=techniques.find(x=>x.id===b.dataset.technique);if(!state.learned.includes(t.id)){if(state.stones<t.cost){toast('Không đủ linh thạch');return}state.stones-=t.cost;state.learned.push(t.id);log(`<b>Lĩnh ngộ</b> ${t.name}`)}state.activeTechnique=t.id;render();save()}if(b.dataset.cultivate){const min=+b.dataset.cultivate,reward=Math.round(min*2.2*state.settings.auraMultiplier/100);state.cultivation={start:Date.now(),end:Date.now()+min*60000,reward};log(`Bắt đầu nhập định ${min} phút`);render();save()}if(b.id==='menuButton')$('#sidebar').classList.toggle('open');if(b.id==='scanButton'){scanUntil=Date.now()+5000;state.mp=Math.max(0,state.mp-5);renderMap();toast('Thần thức lan tỏa');setTimeout(renderMap,5100)}if(b.id==='restButton'){state.hp=stats().maxHp;state.mp=stats().maxMp;toast('Đã hồi phục');render();save()}if(b.id==='regenerateWorld'){state.worldSeed=Math.floor(Math.random()*999999);generateWorld();log('Thiên địa biến động, cơ duyên đã đổi chỗ');render();save()}if(b.id==='resetButton'&&confirm('Xóa toàn bộ hành trình trên thiết bị này?')){localStorage.removeItem(SAVE_KEY);location.reload()}});
document.addEventListener('input',e=>{if(e.target.dataset.setting){state.settings[e.target.dataset.setting]=+e.target.value;renderAdmin();save()}});
document.addEventListener('keydown',e=>{if($('dialog[open]'))return;const d={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]}[e.key];if(d){e.preventDefault();move(...d)}});
$('#setupForm').addEventListener('submit',()=>{state.name=$('#nameInput').value.trim()||'Vô Danh';state.profession=$('#professionInput').value;state.created=true;log(`<b>${state.name}</b> bước vào tiên lộ với nghề ${professions[state.profession].name}`);generateWorld();save();setTimeout(render)});
$('#professionInput').innerHTML=Object.entries(professions).map(([k,v])=>`<option value="${k}">${v.name} — ${v.bonus}</option>`).join('');
if(!state.created)$('#setupDialog').showModal();checkOffline();generateWorld();render();save();setInterval(()=>{checkOffline();renderCultivation();save()},30000);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
