using TuTien.Domain;
namespace TuTien.Application.Dtos;
public record RegisterRequest(string UserName, string Email, string Password);
public record LoginRequest(string UserName, string Password);
public record TokenResponse(string AccessToken, string RefreshToken, DateTime ExpiresAtUtc, string Role);
public record RefreshRequest(string RefreshToken);
public record CreatePlayerRequest(string Name, string ProfessionCode, string? IdempotencyKey);
public record ProfessionDto(Guid Id, string Code, string Name, string Description, string PrimaryBonusText, string SecondaryBonusText, int AttackBonus, int DefenseBonus, int SpiritBonus);
public record PlayerProfileDto(Guid Id, string Name, string ProfessionCode, string ProfessionName, int Level, string Realm, int RealmStage, int CultivationXp, int XpRequired, int Hp, int MaxHp, int Mp, int MaxMp, int Attack, int Defense, int Spirit, int Agility, int Fortune, int Stability, int SpiritStones, int ProfessionPoints, int ExtremePoints, bool RealmLocked, int MapX, int MapY, string? ActiveTechniqueCode, int PityScore);
public record VisibleEntityDto(string Kind, Guid Id, string Name, int X, int Y, string? Extra);
public record WorldSnapshotDto(int Width, int Height, int PlayerX, int PlayerY, IReadOnlyList<int[]> Discovered, IReadOnlyList<VisibleEntityDto> Entities, string ZoneName, decimal Aura);
public record MoveRequest(int X, int Y);
public record CombatStateDto(Guid SessionId, string MonsterName, int MonsterHp, int MonsterMaxHp, int PlayerHp, int PlayerMaxHp, string Status, IReadOnlyList<string> Log);
public record StartCombatRequest(Guid SpawnId, string? IdempotencyKey);
public record CombatActionRequest(CombatActionType Action, Guid? ItemId, string? IdempotencyKey);
public record InventoryItemDto(Guid Id, Guid DefinitionId, string Code, string Name, string Icon, string Type, string Quality, int Quantity, bool Equipped, bool Locked, int Attack, int Defense, int Spirit, int HealAmount, string? PreferredProfession, int ProfessionBonusPercent, bool ProfessionMatch);
public record EquipRequest(Guid ItemId, string? IdempotencyKey);
public record TechniqueDto(Guid Id, string Code, string Name, string Description, string Kind, int LearnCost, bool Learned, bool Active, bool LocksRealm, string? Warning);
public record LearnTechniqueRequest(string Code, string? IdempotencyKey);
public record ChestDto(Guid Id, string Name, string Quality, int X, int Y);
public record OpenChestRequest(Guid ChestId, string? IdempotencyKey);
public record RewardLineDto(string Type, string Text, int Quantity);
public record StartCultivationRequest(int Minutes, string? IdempotencyKey);
public record CultivationStatusDto(Guid? SessionId, string Status, DateTime? EndUtc, int? ExpectedXp, bool CanSettle);
public record RumorDto(Guid Id, string Kind, string Title, string Body, string ApproximateZone, int Reliability, DateTime ExpiresAtUtc);
public record TravelLocationDto(Guid Id, string Code, string Name, int DistanceKm);
public record CheckInRequest(Guid LocationId, string? IdempotencyKey);
public record AdminMonsterDto(Guid Id, string Code, string Name, string Kind, int SpawnWeight, int Hp, int Attack);
public record UpdateSpawnWeightRequest(int SpawnWeight);
public record UpdateAuraRequest(decimal Multiplier);
public record ToggleEventRequest(bool Enabled);
public record StatusDto(Guid Id, string Code, string Name, string Icon, string Polarity, int Stacks, int RemainingTurns, DateTime? ExpiresAtUtc, string Source);
